name: Passport Daily Commits

on:
  workflow_dispatch:    # manual trigger for backdating
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Pinkberry2090"
          git config --global user.email "ositaonyi.2090@gmail.com"

      - name: Ensure tracker file exists
        run: |
          if [ ! -f daily_commits.txt ]; then
            echo "Daily commit tracker for Passport" > daily_commits.txt
          fi

      - name: Create backdated commits (last 120 days)
        run: |
          if [ ! -f backdated_done.flag ]; then
            for i in {120..1}; do
              DATE=$(date -d "$i days ago" +"%Y-%m-%dT12:00:00")
              echo "Backdated commit $DATE" >> daily_commits.txt
              GIT_AUTHOR_DATE=$DATE GIT_COMMITTER_DATE=$DATE git add daily_commits.txt
              GIT_AUTHOR_DATE=$DATE GIT_COMMITTER_DATE=$DATE git commit -m "Backdated commit $DATE"
            done
            touch backdated_done.flag
            git add backdated_done.flag
            git commit -m "Backdate completed flag"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          fi

      - name: Daily commit
        run: |
          echo "Commit for $(date)" >> daily_commits.txt
          git add daily_commits.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
