name: Passport Daily Commits (Fixed Year)

on:
  workflow_dispatch:    # manual trigger
  schedule:
    - cron: "0 0 * * *" # runs daily

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Pinkberry2090"
          git config --global user.email "ositaonyi.2090@gmail.com"

      - name: Ensure tracker file exists
        run: |
          if [ ! -f daily_commits.txt ]; then
            echo "Daily commit tracker for Passport" > daily_commits.txt
          fi

      - name: Create backdated commits from 2022
        run: |
          if [ ! -f backdated_done.flag ]; then
            for i in {120..1}; do
              # Adjust the date manually to 2022–2025 range
              BASE_YEAR=$((2022 + (i / 40)))  # spreads commits across 2022, 2023, 2024, 2025
              MONTH=$(( (i % 12) + 1 ))
              DAY=$(( (i % 28) + 1 ))
              DATE=$(printf "%04d-%02d-%02dT12:00:00" $BASE_YEAR $MONTH $DAY)
              echo "Backdated commit $DATE" >> daily_commits.txt
              GIT_AUTHOR_DATE=$DATE GIT_COMMITTER_DATE=$DATE git add daily_commits.txt
              GIT_AUTHOR_DATE=$DATE GIT_COMMITTER_DATE=$DATE git commit -m "Backdated commit $DATE"
            done
            touch backdated_done.flag
            git add backdated_done.flag
            git commit -m "Backdate completed flag"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          fi

      - name: Daily commit
        run: |
          echo "Commit for $(date)" >> daily_commits.txt
          git add daily_commits.txt
          git commit -m "Daily commit $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
